version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment: 
            AWS_ACCESS_KEY_ID : ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            REGION: ${REGION}
        